version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    container_name: db
    hostname: db
    restart: always
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  backend:
    image: kcehna/foodgramm-backend:latest
    container_name: backend
    hostname: backend
    restart: always
    volumes:
      - data_value:/app/data/
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    links:
      - db
    env_file:
      - ./.env

  frontend:
    image: kcehna/foodgramm-frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend


  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    hostname: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - frontend


volumes:
  database:
  data_value:
  static_value:
  media_value:
