version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    container_name: db
    hostname: db
    restart: always
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    networks:
      - localapp

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/

volumes:
  database:

networks:
  localapp:
